name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_031DB4BF85FC7F14369CC64E12043F1F44281789C3D7260B0207B34582E1F3E928E6B2B49C813B193407D9B296D04A9FC065A48C0DC3625388F4351C61DFA7E709D238E0F5D77314E545CB5D7A9C5315A6958BFEDB7A4BC1894A78F1821ED3B475E66D65815E8E09104965416045FF2D5254CB94FA24BEEB8CF793C85948EEF32AAE859123310EA065D89F1C6E5951067EAE2E8C17E44F095730ED009E3F4BF6CD53C2C65EBE90B15A65131B99DF37D8DB3D8A511D7FA21F1D65E55167964631538824CD4DBC3C1F42F75F37722FDE9412826C47BDB1465676D33D7BC9C7D83C86285398A84503C50FD3300C908C7633F6163913B9B947667F8B72BD9A844F21451A187CD30F56F388593E2B7D2DB813DF88ECAEB08D941893CAF6FCC0322C73C3C0D648588B3104F4AE908464CD2DD67235E360A9A4888F7F8379D1363FAE90DE229BF877939462254B827C8D0BE9C28348752FB7DBC9EFB402B4167D8B49BFC6FD3EC1C07E5B5C7C62BB716A263FCA151471C9' }}

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Run ESLint
        run: npm run eslint

  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile Source Files
        run: npm run build

      - name: Install Latest Test Types
        run: npm run test-setup

      - name: Compile Test Files
        run: npm run test-compile

      - name: Build Test Place File
        run: npm run test-rojo

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        run: Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $((Resolve-Path .\\actions.ovpn).Path)"

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "159.223.100.103") {
                break
              }
            } catch {}
            if ($elapsed -ge 20) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ env.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ env.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: npm run test-run

      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'

      - name: Report Coverage
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
