name: Restart Failed Jobs

on:
  issue_comment:
    types:
      - created

jobs:
  restart-failed-jobs:
    name: Restart Failed Jobs
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '!restart') }}
    steps:
      - name: Add Reaction
        uses: actions/github-script@v6.1.0
        with:
          script: |
            const WHITELIST = new Set([ "osyrisrblx" ]);

            const commentName = context.payload.comment.user.login;
            const issueName = context.payload.issue.user.login;
            if (commentName === issueName || WHITELIST.has(commentName)) {
              const { owner, repo } = context.issue;

              github.rest.reactions.createForIssueComment({
                owner,
                repo,
                comment_id: context.payload.comment.id,
                content: "+1",
              });

              const check_runs = (await github.rest.checks.listForRef({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                ref: context.payload.issue.pull_request.head.sha,
              })).data.check_runs;

              for (const run of check_runs) {
                if (run.app.slug == 'github-actions') {
                  github.actions.reRunWorkflow({ owner, repo, run_id: run.id });
                }
              }
            }

      - name: Restart Failed Jobs
        run: gh run rerun --failed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
